name: CI
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Pylint
        run: |
          pip install pylint
          pylint *.py
      - name: Build Docker
        run: docker build . -t my-app
